import { beforeEach, describe, expect, it } from 'vitest';
import { createSeed } from '../data/seed';
import { PAYMENT_METHODS, type BookingInput, type Database, type User } from '../types';
import { addDays, dateKey, instant, periodRange, weekStart } from './date';
import { availableSlots, changeStatus, createBooking, rescheduleBooking, saveService, saveSettings, saveStaff, validateBooking, validateSchedule } from './domain';
import { dateSchema, registerSchema } from './validation';
const now = new Date('2026-09-09T00:00:00Z');
let db: Database, admin: User, customer: User, staff: User;
let input: BookingInput;
beforeEach(() => { db = createSeed(now); db.bookings = []; admin = db.users[0]; customer = db.users.find(u => u.id === 'customer-1')!; staff = db.users.find(u => u.staffId === 'staff-1')!; input = { customerId: customer.id, serviceId: 'svc-1', staffId: 'staff-1', date: '2026-09-10', time: '10:00', paymentMethod: 'GCash', notes: 'A quiet room, please.' }; });
describe('Booking & availability', () => {
  it('books UTC timestamps and snapshots the service, price, duration, and payment method', () => { const b = createBooking(db, admin, input, now); expect(b.start).toBe('2026-09-10T02:00:00.000Z'); expect(b.end).toBe('2026-09-10T03:00:00.000Z'); expect(b.status).toBe('Confirmed'); expect(b.price).toBe(95); expect(b.paymentMethod).toBe('GCash'); expect(db.notifications[0].type).toBe('booking.created'); });
  it('accepts Philippine payment choices and rejects unsupported methods', () => { for (const paymentMethod of PAYMENT_METHODS) expect(() => validateBooking(db, { ...input, paymentMethod }, now)).not.toThrow(); expect(() => validateBooking(db, { ...input, paymentMethod: 'Credit card' as never }, now)).toThrow(/payment method/); });
  it('creates pending customer requests', () => { expect(createBooking(db, customer, input, now).status).toBe('Pending'); });
  it('prevents identical and partially overlapping provider bookings', () => { createBooking(db, admin, input, now); for (const time of ['09:15', '09:30', '09:45', '10:00', '10:15', '10:45']) expect(() => createBooking(db, admin, { ...input, customerId: 'customer-2', time }, now)).toThrow(/already booked/); });
  it('allows adjacent bookings and another provider at the same time', () => { createBooking(db, admin, input, now); expect(() => createBooking(db, admin, { ...input, time: '11:00' }, now)).not.toThrow(); expect(() => createBooking(db, admin, { ...input, customerId: 'customer-2', staffId: 'staff-2' }, now)).not.toThrow(); });
  it('blocks customer overlaps across different providers', () => { createBooking(db, admin, input, now); expect(() => createBooking(db, admin, { ...input, staffId: 'staff-2' }, now)).toThrow(/customer already/); });
  it('rejects past dates and times', () => { expect(() => validateBooking(db, { ...input, date: '2026-09-08' }, now)).toThrow(/future/); expect(() => validateBooking(db, { ...input, date: '2026-09-09', time: '07:00' }, now)).toThrow(/future/); });
  it('rejects invalid dates, malformed times and non-slot minutes', () => { for (const date of ['2026-02-30', '2026-13-01', 'bad']) expect(() => validateBooking(db, { ...input, date }, now)).toThrow(); for (const time of ['25:00', '10:99', '10:05']) expect(() => validateBooking(db, { ...input, time }, now)).toThrow(); });
  it('rejects closed days, holidays, and staff days off', () => { expect(() => validateBooking(db, { ...input, date: '2026-09-13' }, now)).toThrow(/availability/); db.settings.closedDates = [input.date]; expect(() => validateBooking(db, input, now)).toThrow(/closed date/); db.settings.closedDates = []; db.staff[0].daysOff = [input.date]; expect(() => validateBooking(db, input, now)).toThrow(/closed date/); });
  it('rejects slots outside business hours and slots that end after closing', () => { for (const time of ['08:45', '17:15', '18:00']) expect(() => validateBooking(db, { ...input, time }, now)).toThrow(/availability/); expect(() => validateBooking(db, { ...input, time: '17:00' }, now)).not.toThrow(); });
  it('intersects provider and business availability', () => { db.staff[0].schedule.find(d => d.day === 4)!.start = '11:00'; expect(() => validateBooking(db, input, now)).toThrow(/availability/); expect(availableSlots(db, input, now)[0]).toBe('11:00'); });
  it('rejects inactive services, inactive providers and unassigned services', () => { db.services[0].active = false; expect(() => validateBooking(db, input, now)).toThrow(/service is unavailable/); db.services[0].active = true; db.staff[0].active = false; expect(() => validateBooking(db, input, now)).toThrow(/provider is unavailable/); db.staff[0].active = true; expect(() => validateBooking(db, { ...input, serviceId: 'svc-2' }, now)).toThrow(/provider is unavailable/); });
  it('excludes booked slots but includes the same appointment when rescheduling', () => { const b = createBooking(db, admin, input, now); expect(availableSlots(db, input, now)).not.toContain('10:00'); expect(availableSlots(db, input, now, b.id)).toContain('10:00'); });
});
describe('Rescheduling and cancellations', () => {
  it('reschedules atomically, keeps the price, updates payment preference, and releases old availability', () => { const b = createBooking(db, admin, input, now); const moved = rescheduleBooking(db, admin, b.id, { ...input, time: '14:00', paymentMethod: 'Maya' }, now); expect(moved.id).toBe(b.id); expect(moved.start).toBe('2026-09-10T06:00:00.000Z'); expect(moved.price).toBe(95); expect(moved.paymentMethod).toBe('Maya'); expect(availableSlots(db, input, now)).toContain('10:00'); expect(db.notifications[0].type).toBe('booking.rescheduled'); });
  it('retains original details when a reschedule conflicts', () => { const b = createBooking(db, admin, input, now); createBooking(db, admin, { ...input, customerId: 'customer-2', time: '14:00' }, now); const prior = structuredClone(b); expect(() => rescheduleBooking(db, admin, b.id, { ...input, time: '14:00' }, now)).toThrow(/already booked/); expect(b).toEqual(prior); });
  it('cancellation frees the slot, records history and queues a notification', () => { const b = createBooking(db, customer, input, now); changeStatus(db, customer, b.id, 'Cancelled', now); expect(b.status).toBe('Cancelled'); expect(db.bookings).toHaveLength(1); expect(availableSlots(db, input, now)).toContain('10:00'); expect(db.notifications[0].type).toBe('booking.status_changed'); });
  it('prevents edits and reactivation of closed appointments', () => { const b = createBooking(db, admin, input, now); changeStatus(db, admin, b.id, 'Cancelled', now); expect(() => rescheduleBooking(db, admin, b.id, { ...input, time: '14:00' }, now)).toThrow(/upcoming active/); expect(() => changeStatus(db, admin, b.id, 'Confirmed', now)).toThrow(/already closed/); });
  it('prevents premature completion and no-show status', () => { const b = createBooking(db, admin, input, now); expect(() => changeStatus(db, admin, b.id, 'Completed', now)).toThrow(/end time/); expect(() => changeStatus(db, admin, b.id, 'No-show', now)).toThrow(/after.*starts/); changeStatus(db, admin, b.id, 'Completed', new Date(b.end)); expect(b.status).toBe('Completed'); });
  it('customers cannot cancel past appointments or alter service/customer during rescheduling', () => { const b = createBooking(db, customer, input, now); expect(() => changeStatus(db, customer, b.id, 'Cancelled', new Date(b.start))).toThrow(/upcoming/); expect(() => rescheduleBooking(db, customer, b.id, { ...input, serviceId: 'svc-3' }, now)).toThrow(/original/); });
});
describe('Roles and admin management', () => {
  it('denies cross-customer booking and management', () => { expect(() => createBooking(db, customer, { ...input, customerId: 'customer-2' }, now)).toThrow(/yourself/); const b = createBooking(db, admin, { ...input, customerId: 'customer-2' }, now); expect(() => changeStatus(db, customer, b.id, 'Cancelled', now)).toThrow(/access denied/); expect(() => changeStatus(db, customer, createBooking(db, customer, { ...input, time: '14:00' }, now).id, 'Confirmed', now)).toThrow(/only cancel/); });
  it('limits staff to their own appointments', () => { const b = createBooking(db, admin, { ...input, staffId: 'staff-2' }, now); expect(() => changeStatus(db, staff, b.id, 'Cancelled', now)).toThrow(/access denied/); expect(() => createBooking(db, staff, { ...input, staffId: 'staff-2' }, now)).toThrow(/own appointments/); });
  it('creates, edits and deactivates services without changing booking history', () => { const b = createBooking(db, admin, input, now); saveService(db, admin, { ...db.services[0], price: 130, duration: 90, active: false }); expect(b.price).toBe(95); expect(b.duration).toBe(60); expect(db.services[0].price).toBe(130); saveService(db, admin, { ...db.services[0], id: '', name: 'New service' }); expect(db.services).toHaveLength(7); });
  it('validates service duration, price, uniqueness, and admin permissions', () => { expect(() => saveService(db, admin, { ...db.services[0], duration: 22 })).toThrow(); expect(() => saveService(db, admin, { ...db.services[0], price: -1 })).toThrow(); expect(() => saveService(db, admin, { ...db.services[0], id: '' })).toThrow(/already exists/); expect(() => saveService(db, customer, db.services[0])).toThrow(/administrator/); expect(() => saveService(db, staff, db.services[0])).toThrow(/administrator/); });
  it('prevents staff schedule reductions, days off, deactivation or unassignment that conflict with bookings', () => { createBooking(db, admin, input, now); for (const patch of [{ active: false }, { daysOff: [input.date] }, { serviceIds: ['svc-3'] }, { schedule: db.staff[0].schedule.map(d => ({ ...d, start: '12:00' })) }]) expect(() => saveStaff(db, admin, { ...db.staff[0], ...patch }, now)).toThrow(/conflicts/); });
  it('saves valid staff profiles and creates a linked staff account', () => { saveStaff(db, admin, { ...db.staff[0], name: 'Olivia Wu' }, now); expect(db.users.find(u => u.staffId === 'staff-1')?.name).toBe('Olivia Wu'); saveStaff(db, admin, { ...db.staff[0], id: '', name: 'New Provider', email: 'new@example.com' }, now); expect(db.staff).toHaveLength(6); expect(db.users.find(u => u.email === 'new@example.com')?.role).toBe('staff'); });
  it('blocks conflicting business closures and accepts valid business settings', () => { createBooking(db, admin, input, now); expect(() => saveSettings(db, admin, { ...db.settings, closedDates: [input.date] }, now)).toThrow(/conflict/); saveSettings(db, admin, { ...db.settings, name: 'New Studio Name', closedDates: ['2026-09-12'] }, now); expect(db.settings.name).toBe('New Studio Name'); });
  it('validates schedules and registration contact details', () => { expect(() => validateSchedule([])).toThrow(); expect(() => validateSchedule(db.settings.schedule.map(d => ({ ...d, end: '08:00' })))).toThrow(/closing after/); expect(() => registerSchema.parse({ name: 'A', email: 'wrong', phone: 'xx', password: 'short' })).toThrow(); });
});
describe('Business timezone and date boundaries', () => {
  it('uses Manila dates across UTC midnight', () => { expect(dateKey('2026-09-09T18:00:00Z')).toBe('2026-09-10'); expect(instant('2026-09-10', '09:00').toISOString()).toBe('2026-09-10T01:00:00.000Z'); });
  it('handles month boundaries, Monday weeks and leap dates', () => { expect(addDays('2026-12-31', 1)).toBe('2027-01-01'); expect(weekStart('2026-09-13')).toBe('2026-09-07'); expect(periodRange('2028-02-15', 'month')).toEqual(['2028-02-01', '2028-02-29']); expect(dateSchema.safeParse('2028-02-29').success).toBe(true); });
});

