import { useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Download, Filter, LayoutList, Plus, Search, X } from 'lucide-react';
import type { Booking, Database, User } from '../types';
import { STATUSES } from '../types';
import { addDays, dateKey, formatDate, formatTime, instant, money, periodRange, timeKey, weekStart } from '../lib/date';
import { Avatar, Badge, downloadCSV, Empty } from '../components/ui';
import { BookingTable, DateNavigator } from './Dashboard';
export default function Appointments({ db, user, calendar = false, onBook, onSelect, search, setSearch }: { db: Database; user: User; calendar?: boolean; onBook: (date?: string) => void; onSelect: (b: Booking) => void; search: string; setSearch: (value: string) => void }) {
  const customer = user.role === 'customer';
  const [date, setDate] = useState(dateKey()), [period, setPeriod] = useState(calendar ? 'week' : customer ? 'all' : 'day'), [view, setView] = useState(calendar ? 'calendar' : 'list');
  const [status, setStatus] = useState(''), [service, setService] = useState(''), [staff, setStaff] = useState(''), [filters, setFilters] = useState(false), [page, setPage] = useState(1);
  const filtered = useMemo(() => { const [start, end] = periodRange(date, period); return db.bookings.filter(b => { const name = db.users.find(u => u.id === b.customerId); return (period === 'all' || (dateKey(b.start) >= start && dateKey(b.start) <= end)) && (!status || b.status === status) && (!service || b.serviceId === service) && (!staff || b.staffId === staff) && (!search || `${name?.name} ${name?.email} ${b.id} ${b.serviceName}`.toLowerCase().includes(search.toLowerCase())); }).sort((a, b) => customer ? b.start.localeCompare(a.start) : a.start.localeCompare(b.start)); }, [db, date, period, status, service, staff, search, customer]);
  const pages = Math.max(1, Math.ceil(filtered.length / 10)); const currentPage = Math.min(page, pages); const paginated = filtered.slice((currentPage - 1) * 10, currentPage * 10);
  function exportRows() { downloadCSV('morrow-appointments.csv', [['Reference', 'Customer', 'Service', 'Provider', 'Start (UTC)', 'End (UTC)', 'Timezone', 'Status', 'Price (USD)'], ...filtered.map(b => [b.id, db.users.find(u => u.id === b.customerId)?.name || '', b.serviceName, db.staff.find(s => s.id === b.staffId)?.name || '', b.start, b.end, 'Asia/Taipei', b.status, b.price])]); }
  return <><div className="page-heading"><div><div className="eyebrow">{customer ? 'YOUR TIME, WELL SPENT' : 'A PLACE FOR EVERY APPOINTMENT'}</div><h1>{customer ? 'My bookings' : calendar ? 'Your calendar' : 'Appointments'}</h1><p>{customer ? 'Your upcoming moments of care, and a little history.' : 'Keep every appointment and every detail in view.'}</p></div><div className="button-group"><button className="btn secondary" onClick={exportRows}><Download size={16}/>Export</button><button className="btn primary" onClick={() => onBook()}><Plus size={17}/>{customer ? 'Book an appointment' : 'New appointment'}</button></div></div>
    {customer && <div className="customer-summary"><span><CalendarDays size={22}/><strong>{db.bookings.filter(b => ['Pending', 'Confirmed'].includes(b.status) && Date.parse(b.start) > Date.now()).length}</strong>upcoming appointments</span><span><strong>{db.bookings.filter(b => b.status === 'Completed').length}</strong>moments of care so far</span></div>}
    <section className="panel appointment-panel"><div className="appointment-toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search appointments" placeholder={customer ? 'Search your bookings…' : 'Search customer, service, or booking ID…'} value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/>{search && <button className="icon-btn" aria-label="Clear search" onClick={() => setSearch('')}><X size={14}/></button>}</div><button className={`btn secondary ${filters ? 'pressed' : ''}`} onClick={() => setFilters(!filters)}><Filter size={16}/>Filters{[status, service, staff].filter(Boolean).length > 0 && <span className="count-bubble">{[status, service, staff].filter(Boolean).length}</span>}</button><div className="segmented view-switch"><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><LayoutList size={16}/>List</button><button className={view === 'calendar' ? 'active' : ''} onClick={() => { setView('calendar'); if (period === 'all') setPeriod('week'); }}><CalendarDays size={16}/>Calendar</button></div></div>
      {filters && <div className="filter-row"><label>Status<select aria-label="Filter by status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{STATUSES.map(s => <option key={s}>{s}</option>)}</select></label><label>Service<select aria-label="Filter by service" value={service} onChange={e => { setService(e.target.value); setPage(1); }}><option value="">All services</option>{db.services.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Provider<select aria-label="Filter by provider" value={staff} onChange={e => { setStaff(e.target.value); setPage(1); }}><option value="">All providers</option>{db.staff.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select></label><button className="text-btn" onClick={() => { setStatus(''); setService(''); setStaff(''); setSearch(''); }}>Clear filters<X size={14}/></button></div>}
      <div className="calendar-toolbar"><div className="segmented">{['day', 'week', 'month', ...(view === 'list' ? ['all'] : [])].map(p => <button key={p} className={period === p ? 'active' : ''} onClick={() => { setPeriod(p); setPage(1); }}>{p === 'all' ? 'All dates' : p.charAt(0).toUpperCase() + p.slice(1)}</button>)}</div>{period !== 'all' && <DateNavigator date={date} onChange={d => { setDate(d); setPage(1); }} step={period === 'week' ? 7 : period === 'month' ? 28 : 1}/>}</div>
      {view === 'calendar' ? <CalendarGrid db={db} bookings={filtered} date={date} period={period} onBook={onBook} onSelect={onSelect}/> : customer ? <div className="customer-bookings">{paginated.length ? paginated.map(b => <button className="customer-booking-card" key={b.id} onClick={() => onSelect(b)}><div className="booking-date-block"><span>{formatDate(b.start, { month: 'short' })}</span><strong>{formatDate(b.start, { day: 'numeric' })}</strong></div><div className="booking-card-copy"><h3>{b.serviceName}</h3><p>{formatTime(b.start)} · {b.duration} minutes · {db.staff.find(s => s.id === b.staffId)?.name}</p><small>{b.id}</small></div><Badge status={b.status}/><strong>{money(b.price)}</strong><ChevronRight size={18}/></button>) : <Empty title="Your next moment of care starts here" text="No bookings match your filters. Choose another date or book a new appointment."/>}</div> : <BookingTable bookings={paginated} db={db} onSelect={onSelect}/>}
      {view === 'list' && <div className="pagination"><span>{filtered.length ? `${(currentPage - 1) * 10 + 1}–${Math.min(currentPage * 10, filtered.length)} of ${filtered.length}` : '0'} appointments</span><div><button className="icon-btn" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)} aria-label="Previous page"><ChevronLeft size={17}/></button><span>Page {currentPage} of {pages}</span><button className="icon-btn" disabled={currentPage >= pages} onClick={() => setPage(currentPage + 1)} aria-label="Next page"><ChevronRight size={17}/></button></div></div>}
    </section><div className="page-footnote"><span className="live-dot"/>Your calendar stays in sync with every booking. All times in Taipei (UTC+08:00).</div></>;
}
function CalendarGrid({ db, bookings, date, period, onBook, onSelect }: { db: Database; bookings: Booking[]; date: string; period: string; onBook: (date?: string) => void; onSelect: (b: Booking) => void }) {
  if (period === 'month') { const monthStart = `${date.slice(0, 7)}-01`, start = weekStart(monthStart), days = Array.from({ length: 42 }, (_, i) => addDays(start, i)); return <div className="month-scroll"><div className="month-calendar">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => <div className="month-weekday" key={d}>{d}</div>)}{days.map(d => <div className={`month-day ${d.slice(0, 7) !== date.slice(0, 7) ? 'outside' : ''}`} key={d}><button className={`day-number ${d === dateKey() ? 'today' : ''}`} onClick={() => onBook(d)} disabled={d < dateKey()} aria-label={`Book on ${formatDate(d)}`}>{Number(d.slice(-2))}<Plus size={12}/></button>{bookings.filter(b => dateKey(b.start) === d).map(b => <button key={b.id} className={`month-event ${db.services.find(s => s.id === b.serviceId)?.color} ${b.status === 'Cancelled' ? 'event-cancelled' : ''}`} onClick={() => onSelect(b)} title={`${formatTime(b.start)} · ${b.serviceName}`}><b>{timeKey(b.start)}</b> {db.users.find(u => u.id === b.customerId)?.name.split(' ')[0] || b.serviceName}</button>)}</div>)}</div></div>; }
  const days = Array.from({ length: period === 'day' ? 1 : 7 }, (_, i) => addDays(period === 'day' ? date : weekStart(date), i));
  return <div className="week-scroll"><div className={`week-calendar ${period === 'day' ? 'single-day' : ''}`} style={{ gridTemplateColumns: `54px repeat(${days.length}, minmax(${period === 'day' ? '220' : '118'}px, 1fr))` }}><div className="time-header">GMT+8</div>{days.map(d => <div className={`week-day-header ${d === dateKey() ? 'today' : ''}`} key={d}><span>{formatDate(d, { weekday: 'short' })}</span><strong>{formatDate(d, { day: 'numeric' })}</strong></div>)}<div className="time-axis">{Array.from({ length: 13 }, (_, h) => <span key={h}>{String(h + 7).padStart(2, '0')}:00</span>)}</div>{days.map(d => { const daily = bookings.filter(b => dateKey(b.start) === d); return <div className="day-column" key={d}>{Array.from({ length: 13 }, (_, h) => <button key={h} className="hour-slot" onClick={() => onBook(d)} disabled={instant(d, `${String(h + 7).padStart(2, '0')}:00`).getTime() < Date.now()} aria-label={`New appointment ${formatDate(d)} ${h + 7}:00`}/>)}{daily.map(b => { const start = timeKey(b.start).split(':').map(Number); const overlapping = daily.filter(other => other.start < b.end && other.end > b.start).sort((a,b) => a.id.localeCompare(b.id)); const index = overlapping.findIndex(other => other.id === b.id); return <button key={b.id} className={`calendar-event ${db.services.find(s => s.id === b.serviceId)?.color} ${b.status === 'Cancelled' ? 'event-cancelled' : ''}`} style={{ top: `${(start[0] - 7 + start[1] / 60) * 70}px`, height: `${Math.max(33, b.duration / 60 * 70 - 3)}px`, left: `${index / overlapping.length * 100}%`, width: `${100 / overlapping.length}%` }} onClick={() => onSelect(b)} title={`${b.serviceName} · ${formatTime(b.start)} · ${b.status}`}><small>{timeKey(b.start)}</small><strong>{db.users.find(u => u.id === b.customerId)?.name || b.serviceName}</strong><span>{b.serviceName}</span>{period === 'day' && <span className="event-provider"><Avatar name={db.staff.find(s => s.id === b.staffId)?.name || 'Provider'} small/>{db.staff.find(s => s.id === b.staffId)?.name}</span>}</button>; })}</div>; })}</div></div>;
}
