import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Plus, Users, ArrowRight, Sparkles } from 'lucide-react';
import type { Booking, Database, Page, User } from '../types';
import { addDays, addMonths, dateKey, formatDate, formatTime, money, periodRange, weekStart } from '../lib/date';
import { Avatar, Badge, Empty, PanelHeading } from '../components/ui';
export function BookingTable({ bookings, db, onSelect, compact = false }: { bookings: Booking[]; db: Database; onSelect: (b: Booking) => void; compact?: boolean }) {
  if (!bookings.length) return <Empty title="No appointments found" text="Try a different date or filter, or create a new appointment."/>;
  return <div className="table-scroll"><table className="booking-table"><thead><tr><th>Customer</th><th>Service</th><th>{compact ? 'Time' : 'Date & time'}</th><th>Provider</th><th>Status</th><th aria-label="Open appointment"/></tr></thead><tbody>{bookings.map(b => { const customer = db.users.find(u => u.id === b.customerId); const staff = db.staff.find(s => s.id === b.staffId); const service = db.services.find(s => s.id === b.serviceId); return <tr key={b.id} onClick={() => onSelect(b)}><td><div className="person-cell"><Avatar name={customer?.name || 'Customer'} color={service?.color}/><div><strong>{customer?.name || 'Customer'}</strong><small>{compact ? b.id : customer?.email}</small></div></div></td><td><span className={`service-dot ${service?.color}`}/>{b.serviceName}<small className="under">{b.duration} min · {money(b.price)}</small></td><td><strong>{compact ? formatTime(b.start) : formatDate(b.start, { month: 'short', day: 'numeric' })}</strong><small className="under">{compact ? `to ${formatTime(b.end)}` : formatTime(b.start)}</small></td><td><span className="provider-mini"><span className={`tiny-avatar ${staff?.color}`}>{staff?.name.split(' ').map(n => n[0]).join('')}</span>{staff?.name.split(' ')[0]}</span></td><td><Badge status={b.status}/></td><td><button className="icon-btn" aria-label={`View appointment for ${customer?.name}`} onClick={e => { e.stopPropagation(); onSelect(b); }}><ArrowUpRight size={17}/></button></td></tr>; })}</tbody></table></div>;
}
export default function Dashboard({ db, user, navigate, onBook, onSelect }: { db: Database; user: User; navigate: (p: Page) => void; onBook: () => void; onSelect: (b: Booking) => void }) {
  const today = dateKey(), current = db.bookings.filter(b => dateKey(b.start) === today), activeToday = current.filter(b => !['Cancelled', 'No-show'].includes(b.status));
  const [monthStart, monthEnd] = periodRange(today, 'month');
  const monthBookings = db.bookings.filter(b => dateKey(b.start) >= monthStart && dateKey(b.start) <= monthEnd);
  const revenue = monthBookings.filter(b => b.status === 'Completed').reduce((sum, b) => sum + b.price, 0);
  const week = weekStart(today), chart = Array.from({ length: 7 }, (_, i) => { const date = addDays(week, i); const bookings = db.bookings.filter(b => dateKey(b.start) === date); return { date, confirmed: bookings.filter(b => b.status === 'Confirmed' || b.status === 'Pending').length, completed: bookings.filter(b => b.status === 'Completed').length }; });
  const max = Math.max(6, ...chart.map(c => c.confirmed + c.completed)), totalWeek = chart.reduce((sum, c) => sum + c.confirmed + c.completed, 0);
  const previousWeek = db.bookings.filter(b => dateKey(b.start) >= addDays(week, -7) && dateKey(b.start) < week && !['Cancelled', 'No-show'].includes(b.status)).length;
  const weekChange = previousWeek ? Math.round((totalWeek - previousWeek) / previousWeek * 100) : 0;
  const next = [...current].filter(b => ['Pending', 'Confirmed'].includes(b.status) && Date.parse(b.end) > Date.now()).sort((a, b) => a.start.localeCompare(b.start))[0];
  const services = db.services.map(s => ({ ...s, count: monthBookings.filter(b => b.serviceId === s.id && !['Cancelled', 'No-show'].includes(b.status)).length })).sort((a, b) => b.count - a.count).slice(0, 4);
  const recentDays = Array.from({ length: 7 }, (_, i) => addDays(today, i - 6));
  const sparkline = (measure: (bookings: Booking[]) => number) => {
    const values = recentDays.map(day => measure(db.bookings.filter(b => dateKey(b.start) === day)));
    const max = Math.max(1, ...values);
    return values.map((value, i) => `${i * 12},${28 - value / max * 24}`).join(' ');
  };
  return <><div className="page-heading"><div className="heading-copy"><div className="eyebrow">A LITTLE CLARITY FOR YOUR DAY</div><h1>Good {Number(new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Manila', hour: '2-digit', hour12: false }).format(new Date())) < 12 ? 'morning' : 'afternoon'}, {user.name.split(' ')[0]} <span className="greeting-dot">✳</span></h1><p>Here’s what’s happening at your studio today.</p></div><button className="btn primary" onClick={onBook}><Plus size={17}/>New appointment</button></div>
    <div className="day-banner"><div className="banner-icon"><Sparkles size={23}/></div><div><strong>A well-planned day. A little more peace of mind.</strong><p>You have <b>{activeToday.length} appointments</b> today{current.some(b => b.status === 'Pending') ? ` and ${current.filter(b => b.status === 'Pending').length} awaiting confirmation.` : '. Let’s make each one count.'}</p></div><button onClick={() => navigate('Calendar')}>View your calendar<ArrowRight size={16}/></button></div>
    <div className="stat-grid">{[
      { label: 'Today’s appointments', value: activeToday.length, sub: `${current.filter(b => b.status === 'Completed').length} completed today`, icon: CalendarDays, color: 'sage', points: sparkline(bookings => bookings.filter(b => !['Cancelled', 'No-show'].includes(b.status)).length) },
      { label: 'Pending confirmation', value: db.bookings.filter(b => b.status === 'Pending').length, sub: 'Ready for your attention', icon: Clock3, color: 'sand', points: sparkline(bookings => bookings.filter(b => b.status === 'Pending').length) },
      { label: 'Revenue this month', value: money(revenue), sub: 'From completed appointments', icon: CircleDollarSign, color: 'sage', points: sparkline(bookings => bookings.filter(b => b.status === 'Completed').reduce((sum, b) => sum + b.price, 0)) },
      { label: 'Customers this month', value: new Set(monthBookings.map(b => b.customerId)).size, sub: 'People making time for care', icon: Users, color: 'lavender', points: sparkline(bookings => new Set(bookings.map(b => b.customerId)).size) },
    ].map(s => <div className="stat-card" key={s.label}><div className="stat-top"><span>{s.label}</span><span className={`stat-icon ${s.color}`}><s.icon size={18}/></span></div><div className="stat-value">{s.value}<svg viewBox="0 0 74 32" aria-hidden="true"><polyline points={s.points} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></div><small>{s.sub}</small></div>)}</div>
    <div className="dashboard-charts"><section className="panel bookings-chart"><PanelHeading title="Booking overview" detail="A little perspective on your week" action={user.role === 'admin' ? 'View reports' : 'View calendar'} onAction={() => navigate(user.role === 'admin' ? 'Reports' : 'Calendar')}/><div className="chart-summary"><strong>{totalWeek}<span>appointments this week</span></strong><span className={`trend ${weekChange < 0 ? 'negative' : ''}`}>{weekChange < 0 ? <ArrowDownRight size={14}/> : <ArrowUpRight size={14}/>} {Math.abs(weekChange)}% <em>vs. last week</em></span><div className="chart-legend"><span><i className="legend-dot dark"/>Completed</span><span><i className="legend-dot light"/>Upcoming</span></div></div><div className="bar-chart"><div className="chart-y">{[max, Math.round(max * .75), Math.round(max * .5), Math.round(max * .25), 0].map((v, i) => <span key={i}>{v}</span>)}</div><div className="chart-plot"><div className="chart-gridlines">{[1, 2, 3, 4, 5].map(n => <i key={n}/>)}</div><div className="chart-bars">{chart.map(c => <div className={`bar-column ${c.date === today ? 'is-today' : ''}`} key={c.date}><div className="bar-stack" title={`${formatDate(c.date)}: ${c.completed} completed, ${c.confirmed} upcoming`}><div className="bar upcoming" style={{ height: `${c.confirmed / max * 148}px` }}/><div className="bar completed" style={{ height: `${c.completed / max * 148}px` }}/></div><span>{formatDate(c.date, { weekday: 'short' })}</span></div>)}</div></div></div><div className="chart-footer"><span>{formatDate(week, { month: 'long', day: 'numeric' })} – {formatDate(addDays(week, 6), { month: 'long', day: 'numeric', year: 'numeric' })}</span><span>All times in Manila</span></div></section>
    <section className="panel popular-services"><PanelHeading title="Popular services" detail="What your customers are loving"/><div className="service-ranking">{services.map((s, i) => <div className="ranking-row" key={s.id}><span className={`rank-icon ${s.color}`}>{String(i + 1).padStart(2, '0')}</span><div><div><strong>{s.name}</strong><span>{s.count}<small> bookings</small></span></div><div className="progress-track"><span style={{ width: `${s.count / Math.max(1, services[0].count) * 100}%` }} className={s.color}/></div></div></div>)}</div><button className="panel-bottom-action" onClick={() => navigate('Services')}>Explore all services<ArrowRight size={16}/></button></section></div>
    <div className="dashboard-bottom"><section className="panel today-table"><PanelHeading title="Today’s appointments" detail={`${formatDate(today, { weekday: 'long', month: 'long', day: 'numeric' })} · ${current.length} appointments`} action="View all" onAction={() => navigate('Appointments')}/><BookingTable bookings={[...current].sort((a,b) => a.start.localeCompare(b.start)).slice(0, 5)} db={db} onSelect={onSelect} compact/></section><section className="panel next-up"><div className="next-label"><span className="live-dot"/>UP NEXT</div>{next ? <><span className="next-time">{formatTime(next.start)}<small>{next.duration} min</small></span><h2>{next.serviceName}</h2><div className="next-person"><Avatar name={db.users.find(u => u.id === next.customerId)?.name || 'Customer'}/><div><strong>{db.users.find(u => u.id === next.customerId)?.name}</strong><small>with {db.staff.find(s => s.id === next.staffId)?.name}</small></div></div><Badge status={next.status}/><button className="btn white" onClick={() => onSelect(next)}>Appointment details<ArrowUpRight size={16}/></button></> : <div className="day-complete"><CalendarDays size={32}/><h2>A little breathing room.</h2><p>No more upcoming appointments today.</p><button className="btn white" onClick={() => navigate('Calendar')}>See what’s ahead<ArrowRight size={16}/></button></div>}<div className="next-footer">GOOD CARE STARTS WITH A GOOD PLAN.</div></section></div>
  </>;
}
export function DateNavigator({ date, onChange, step = 1 }: { date: string; onChange: (date: string) => void; step?: number }) { return <div className="date-navigator"><button className="icon-btn" onClick={() => onChange(step === 28 ? addMonths(date, -1) : addDays(date, -step))} aria-label="Previous period"><ChevronLeft size={17}/></button><input type="date" aria-label="Selected date" value={date} onChange={e => e.target.value && onChange(e.target.value)}/><button className="icon-btn" onClick={() => onChange(step === 28 ? addMonths(date, 1) : addDays(date, step))} aria-label="Next period"><ChevronRight size={17}/></button><button className="text-btn" onClick={() => onChange(dateKey())}>Today</button></div>; }
