import { useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, Clock3, Mail, MapPin, Plus, UserRound } from 'lucide-react';
import type { Booking, BookingInput, Database, Status, User } from '../types';
import { api } from '../lib/api';
import { addDays, dateKey, formatDate, formatTime, instant, money, timeKey } from '../lib/date';
import { errorMessage } from '../lib/validation';
import { Avatar, Badge, Empty, ErrorNotice, Field, Modal, SubmitButton } from './ui';
export function BookingForm({ db, user, existing, initialDate, onClose }: { db: Database; user: User; existing?: Booking; initialDate?: string; onClose: () => void }) {
  const [step, setStep] = useState(existing ? 2 : 1), [busy, setBusy] = useState(false), [error, setError] = useState(''), [result, setResult] = useState<Booking | null>(null);
  const customers = db.users.filter(u => u.role === 'customer');
  const [form, setForm] = useState<BookingInput>({ customerId: existing?.customerId || (user.role === 'customer' ? user.id : customers[0]?.id || ''), serviceId: existing?.serviceId || '', staffId: existing?.staffId || (user.role === 'staff' ? user.staffId! : ''), date: existing ? dateKey(existing.start) : initialDate && initialDate >= dateKey() ? initialDate : addDays(dateKey(), 1), time: existing ? timeKey(existing.start) : '', notes: existing?.notes || '' });
  const service = db.services.find(s => s.id === form.serviceId), provider = db.staff.find(s => s.id === form.staffId), customer = db.users.find(u => u.id === form.customerId);
  const staff = db.staff.filter(s => s.active && s.serviceIds.includes(form.serviceId) && (user.role !== 'staff' || s.id === user.staffId));
  const slots = useMemo(() => form.serviceId && form.staffId && form.customerId && form.date ? api.slots({ customerId: form.customerId, serviceId: form.serviceId, staffId: form.staffId, date: form.date }, existing?.id) : [], [form.serviceId, form.staffId, form.customerId, form.date, existing?.id, db]);
  function next(e: FormEvent) { e.preventDefault(); setError(''); if (step === 1) { if (!form.serviceId || !form.customerId) { setError('Select a service and customer to continue.'); return; } setStep(2); } else if (step === 2) { if (!slots.includes(form.time)) { setError('Choose an available time slot.'); return; } setStep(3); } else void submit(); }
  async function submit() { setBusy(true); try { const booking = existing ? await api.reschedule(existing.id, form) : await api.book(form); setResult(booking); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  if (result) return <Modal title={existing ? 'Appointment rescheduled' : 'You’re all booked in'} subtitle="A little time, set aside for care." onClose={onClose}><div className="booking-success"><span className="success-orb"><CheckCircle2 size={39}/></span><h2>{existing ? 'Your new time is saved.' : 'It’s in the calendar.'}</h2><p>{result.status === 'Pending' ? 'Your request has been received. The studio will confirm your appointment.' : 'Your appointment is confirmed. We look forward to seeing you.'}</p><div className="confirmation-card"><span className="eyebrow">{result.id}</span><h3>{result.serviceName}</h3><div><CalendarDays size={17}/>{formatDate(result.start, { weekday: 'long', month: 'long', day: 'numeric' })}</div><div><Clock3 size={17}/>{formatTime(result.start)} · {result.duration} minutes</div><div><UserRound size={17}/>{provider?.name}</div><div><MapPin size={17}/>{db.settings.name}</div><div className="confirmation-total"><Badge status={result.status}/><strong>{money(result.price)}</strong></div></div><p className="muted small-text">You can find this appointment and make changes in your booking history.</p><button className="btn primary full" onClick={onClose}>Done<Check size={17}/></button></div></Modal>;
  return <Modal title={existing ? 'Reschedule appointment' : 'New appointment'} subtitle="Make a little space for feeling better." onClose={onClose} wide><div className="booking-steps">{['Service & customer', 'Date & time', 'Review & book'].map((label, i) => <div key={label} className={step >= i + 1 ? 'active' : ''}><span>{step > i + 1 ? <Check size={13}/> : i + 1}</span>{label}</div>)}</div><form onSubmit={next}><div className="modal-body"><ErrorNotice error={error}/>{step === 1 && <><h3 className="form-section-title">What can we help you with?</h3><div className="service-options">{db.services.filter(s => s.active && (user.role !== 'staff' || db.staff.find(p => p.id === user.staffId)?.serviceIds.includes(s.id))).map(s => <button className={`service-option ${form.serviceId === s.id ? 'selected' : ''}`} key={s.id} type="button" onClick={() => setForm({ ...form, serviceId: s.id, staffId: user.role === 'staff' ? user.staffId! : '', time: '' })}><span className={`service-symbol ${s.color}`}><Plus size={20}/></span><strong>{s.name}</strong><p>{s.description}</p><div><span>{s.duration} min</span><b>{money(s.price)}</b></div>{form.serviceId === s.id && <CheckCircle2 size={18} className="selected-check"/>}</button>)}</div>{user.role !== 'customer' ? <Field label="Customer"><select required value={form.customerId} onChange={e => setForm({ ...form, customerId: e.target.value, time: '' })}><option value="">Select a customer</option>{customers.map(c => <option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></Field> : <div className="info-strip"><UserRound size={17}/>Booking for {user.name} · {user.email}</div>}</>}
      {step === 2 && <><div className="selected-service"><span className={`service-symbol ${service?.color}`}><CalendarDays size={21}/></span><div><strong>{existing?.serviceName ?? service?.name}</strong><p>{existing?.duration ?? service?.duration} minutes · {money(existing?.price ?? service?.price ?? 0)}</p></div></div><Field label="Choose your provider"><select value={form.staffId} required onChange={e => setForm({ ...form, staffId: e.target.value, time: '' })}><option value="">Select a provider</option>{staff.map(s => <option value={s.id} key={s.id}>{s.name} · {s.title}</option>)}</select></Field><Field label="Appointment date" hint="All appointment times are in Taipei (UTC+08:00)."><input type="date" value={form.date} min={dateKey()} required onChange={e => setForm({ ...form, date: e.target.value, time: '' })}/></Field><h3 className="form-section-title">Available times</h3>{!form.staffId ? <div className="info-strip">Choose a provider to see their availability.</div> : slots.length ? <div className="time-slots">{slots.map(time => <button type="button" className={form.time === time ? 'selected' : ''} onClick={() => setForm({ ...form, time })} key={time}>{formatTime(instant(form.date, time).toISOString())}</button>)}</div> : <Empty title="No available times" text="This date is closed, fully booked, or in the past. Try another date or provider."/>}</>}
      {step === 3 && <><div className="review-title"><CheckCircle2 size={25}/><div><h3>Everything looking good?</h3><p>Review the details before saving your appointment.</p></div></div><div className="review-grid"><div><small>SERVICE</small><strong>{existing?.serviceName ?? service?.name}</strong><span>{existing?.duration ?? service?.duration} minutes · {money(existing?.price ?? service?.price ?? 0)}</span></div><div><small>DATE & TIME</small><strong>{formatDate(form.date)}</strong><span>{formatTime(instant(form.date, form.time).toISOString())} · Taipei</span></div><div><small>CUSTOMER</small><strong>{customer?.name}</strong><span>{customer?.email}</span></div><div><small>PROVIDER</small><strong>{provider?.name}</strong><span>{provider?.title}</span></div></div><Field label="Appointment notes (optional)"><textarea rows={3} maxLength={1000} value={form.notes} placeholder="Preferences or anything we should know…" onChange={e => setForm({ ...form, notes: e.target.value })}/></Field><div className="info-strip"><CalendarDays size={17}/>You can reschedule or cancel before your appointment starts.</div></>}
    </div><div className="modal-footer"><button type="button" className="btn secondary" onClick={() => step > (existing ? 2 : 1) ? setStep(step - 1) : onClose()} disabled={busy}>{step > (existing ? 2 : 1) ? <><ArrowLeft size={16}/>Back</> : 'Cancel'}</button><SubmitButton busy={busy}>{step === 3 ? existing ? 'Save new appointment time' : 'Book appointment' : <>Continue<ArrowRight size={16}/></>}</SubmitButton></div></form></Modal>;
}
export function BookingDetail({ booking, db, user, onClose, onReschedule, notify }: { booking: Booking; db: Database; user: User; onClose: () => void; onReschedule: (b: Booking) => void; notify: (message: string) => void }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [cancel, setCancel] = useState(false);
  const customer = db.users.find(u => u.id === booking.customerId), provider = db.staff.find(s => s.id === booking.staffId);
  const active = ['Pending', 'Confirmed'].includes(booking.status), future = Date.parse(booking.start) > Date.now();
  async function status(value: Status) { setBusy(true); setError(''); try { await api.status(booking.id, value); notify(`Appointment ${value.toLowerCase()}.`); onClose(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title="Appointment details" subtitle={booking.id} onClose={onClose}><div className="modal-body"><ErrorNotice error={error}/><div className="detail-title"><h2>{booking.serviceName}</h2><Badge status={booking.status}/></div><div className="detail-time"><CalendarDays size={20}/><div><strong>{formatDate(booking.start, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</strong><p>{formatTime(booking.start)} – {formatTime(booking.end)} · Taipei</p></div></div><div className="detail-person"><Avatar name={customer?.name || 'Customer'}/><div><small>CUSTOMER</small><strong>{customer?.name}</strong><a href={`mailto:${customer?.email}`}><Mail size={13}/>{customer?.email}</a><span>{customer?.phone}</span></div></div><div className="detail-person"><Avatar name={provider?.name || 'Provider'} color={provider?.color}/><div><small>PROVIDER</small><strong>{provider?.name}</strong><span>{provider?.title}</span></div></div>{booking.notes && <div className="note-card"><small>APPOINTMENT NOTES</small><p>{booking.notes}</p></div>}<div className="detail-total"><span>{booking.duration} minute session</span><strong>{money(booking.price)}</strong></div>{active && user.role !== 'customer' && <div className="status-actions">{booking.status === 'Pending' && <button className="btn primary" disabled={busy} onClick={() => void status('Confirmed')}><Check size={16}/>Confirm appointment</button>}<button className="btn secondary" disabled={busy || Date.parse(booking.end) > Date.now()} title="Available after the appointment ends" onClick={() => void status('Completed')}>Mark completed</button><button className="btn secondary" disabled={busy || future} title="Available after the appointment starts" onClick={() => void status('No-show')}>Mark no-show</button></div>}{cancel && <div className="cancel-confirm"><strong>Cancel this appointment?</strong><p>The time slot will become available again.</p><div><button className="btn secondary" disabled={busy} onClick={() => setCancel(false)}>Keep appointment</button><button className="btn danger" disabled={busy} onClick={() => void status('Cancelled')}>{busy ? 'Cancelling…' : 'Yes, cancel appointment'}</button></div></div>}</div><div className="modal-footer">{active && (future || user.role !== 'customer') && !cancel ? <button className="text-btn danger-text" onClick={() => setCancel(true)} disabled={busy}>Cancel appointment</button> : <button className="btn secondary" onClick={onClose}>Close</button>}{active && future && <button className="btn primary" onClick={() => onReschedule(booking)} disabled={busy}><CalendarDays size={16}/>Reschedule</button>}</div></Modal>;
}
