import { useEffect, useRef, type ReactNode } from 'react';
import { X, ArrowUpRight, CalendarDays, LoaderCircle, Check, AlertCircle } from 'lucide-react';
import type { Status } from '../types';
export function IconLogo({ small = false }: { small?: boolean }) { return <span className={`logo-mark ${small ? 'small' : ''}`}><img src="/website-icon.png" alt="" aria-hidden="true" /></span>; }
export function Avatar({ name, color = 'sage', small = false }: { name: string; color?: string; small?: boolean }) { return <span className={`avatar ${color} ${small ? 'small' : ''}`}>{name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span>; }
export function Badge({ status }: { status: Status }) { return <span className={`badge ${status.toLowerCase()}`}><span />{status}</span>; }
export function Empty({ title = 'Nothing here just yet', text, action }: { title?: string; text: string; action?: ReactNode }) { return <div className="empty"><span className="empty-icon"><CalendarDays size={25}/></span><h3>{title}</h3><p>{text}</p>{action}</div>; }
export function ErrorNotice({ error }: { error?: string }) { return error ? <div className="error-notice" role="alert"><AlertCircle size={17}/><span>{error}</span></div> : null; }
export function SubmitButton({ busy, children, className = 'btn primary' }: { busy: boolean; children: ReactNode; className?: string }) { return <button className={className} disabled={busy} type="submit">{busy && <LoaderCircle size={16} className="spin"/>}{busy ? 'Saving…' : children}</button>; }
export function Modal({ title, subtitle, children, onClose, wide = false }: { title: string; subtitle?: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDivElement>(null);
  const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; const priorOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; const dialog = ref.current!; const focusable = () => [...dialog.querySelectorAll<HTMLElement>('a[href], button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex="0"]')].filter(e => e.offsetParent !== null); focusable()[0]?.focus(); const handle = (e: KeyboardEvent) => { if (e.key === 'Escape') closeRef.current(); if (e.key === 'Tab') { const nodes = focusable(); const first = nodes[0], last = nodes.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', handle); return () => { document.body.style.overflow = priorOverflow; document.removeEventListener('keydown', handle); previous?.focus(); }; }, []);
  return <div className="modal-overlay" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div className={`modal ${wide ? 'wide' : ''}`} ref={ref} role="dialog" aria-modal="true" aria-label={title}><div className="modal-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</div></div>;
}
export function Toast({ message }: { message: string }) { return <div className="toast" role="status"><Check size={17}/>{message}</div>; }
export function PanelHeading({ title, detail, action, onAction }: { title: string; detail?: string; action?: string; onAction?: () => void }) { return <div className="panel-heading"><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div>{action && <button className="text-btn" onClick={onAction}>{action}<ArrowUpRight size={15}/></button>}</div>; }
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
export function downloadCSV(filename: string, rows: (string | number)[][]) { const csv = rows.map(row => row.map(cell => { const value = String(cell); return `"${(/^[=+\-@\t\r]/.test(value) ? "'" : '') + value.replaceAll('"', '""')}"`; }).join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
